server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.30.17.28:3306/eas?characterEncoding=utf-8&useUnicode=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  application:
    name: order_relation_service
port


security:
  basic:
    enabled: false


#
# #Hibernate ddl auto (validate|create|create-drop|update)
#
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

