server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://172.30.17.28:3306/db_114bmo2o
    data-username: root
    data-password: 123456
  jpa:MYSQL
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

